### ISSUE TITLE
Labels and strings no longer highlighted

### ISSUE THREAD

**Issue by backdround** [earthly/earthly.vim#12]
Latest version (66bf86d):
![image](https://github.com/earthly/earthly.vim/assets/17349169/4a38a810-b073-4cc0-93cb-a9f1be6fd439)
Previous version (8f6beb9):
![image](https://github.com/earthly/earthly.vim/assets/17349169/b36bf200-f747-43ae-8bfe-01693055fe1e)

`:echo synID(line("."), col("."), 1)` says:
`0` and `551` respectively

**Comment by alexcb** [comment]
fixed in cb0440a357a09fb9234ece56a6b09e04d25c1b1d
