### ISSUE TITLE
tree-sitter

### ISSUE THREAD

**Issue by konradmalik** [earthly/earthly.vim#6]
Hey guys,
just a friendly question:
Have you thought about changing this into [Tree-sitter](https://github.com/tree-sitter/tree-sitter) parser implementation?
Then it can be used, for example, with Neovim via [nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter) without installing custom plugins. Tree-sitter recently became a de-facto syntax highlighting etc. solution for Neovim.

Unfortunately, I have zero ideas on how to do it and how much work is needed :(

**Comment by alexcb** [comment]
there's a new repo that implements this: https://github.com/glehmann/tree-sitter-earthfile

**Comment by konradmalik** [comment]
Nice, thanks for the info.

Seems like it's working for me, but lacks highlighting in Neovim (nvim-treesitter issue probably?).

```bash
vim.treesitter: require("vim.treesitter.health").check()

- Nvim runtime ABI version: 14
- OK Parser: earthfile  ABI: 14, path: /nix/store/5fax21wm9x7wrzfz1ivw8l5zd474hm40-vim-pack-dir/pack/myNeovimPackages/start/vimplugin-treesitter-grammar-earthfile/parser/earthfile.so
```
![image](https://github.com/earthly/earthly.vim/assets/13033392/17919969-0791-4a1e-8508-9b7787f78a57)

For the interested on how to use it in a nix flake, [see this commit for reference](https://github.com/konradmalik/neovim-flake/commit/e68ac817046247536e95c784cea11e4dfcaeae2f).

**Comment by alexcb** [comment]
> but lacks highlighting in Neovim

I'm so glad you mentioned that, because I tried it out yesterday (and also _finally_ ported my vimscript to lua) and kept struggling to understand if it was an issue on my setup or not.

If you have the time and experience, I suspect some of the tree-sitter related repos could use your help.

**Comment by alexcb** [comment]
cc @glehmann

**Comment by konradmalik** [comment]
> > but lacks highlighting in Neovim
> 
> I'm so glad you mentioned that, because I tried it out yesterday (and also _finally_ ported my vimscript to lua) and kept struggling to understand if it was an issue on my setup or not.
> 
> If you have the time and experience, I suspect some of the tree-sitter related repos could use your help.

Hmm, after some thinking I see that:
- earthfile support was added to nvim-treesitter last week (April 11th) [here](https://github.com/nvim-treesitter/nvim-treesitter/pull/6395)
- nvim-treesitter in nixpkgs-unstable (the one I use) was last updated "2024-04-03"

This would mean that most probably highlights are not there, because my nvim-treesitter is a bit too old.

**Comment by konradmalik** [comment]
yeah, I was right, there you go:
![image](https://github.com/earthly/earthly.vim/assets/13033392/4aa62b89-f1f8-42f3-9894-81c3823fb329)

@alexcb double check your nvim-treesitter version as well.

For the interested nix-users: [this commit shows how to self-host nvim-treesitter plugin in your flake](https://github.com/konradmalik/neovim-flake/commit/29aaa3efc0b3f7f56e97946676722748c30702c9). This was the only one for which I didn't have full control over the version so it was a bit older.

**Comment by glehmann** [comment]
don’t know if that’s the problem or not, but I had to configure nvim to set the file type for the `Earthfile`s:

~~~lua
vim.filetype.add { filename = { ['Earthfile'] = 'earthfile' } }
~~~

I’ve submitted a patch to vim — which should have been automatically ported to nvim — so unless an unstable nvim is used, I think we still need that command. https://github.com/vim/vim/pull/14408 

For `nvim-treesitter`, I just updated the checkout done by [kickstart.nvim](https://github.com/nvim-lua/kickstart.nvim) in `~/.local/share/nvim/lazy/nvim-treesitter`

Edit: the filetype indeed made it to neovim: https://github.com/neovim/neovim/commit/7560aee59547c3b050c3ee9988dd0e4d36d00144

**Comment by alexcb** [comment]
> but I had to configure nvim to set the file type for the `Earthfile`s:

ah ha! that was the missing part; thanks for pointing that out, it's now working for me (and looks great)!

**Comment by alexcb** [comment]
and it looks like neovim has an Earthfile entry under:

https://github.com/neovim/neovim/blob/6488a9268a6352de63fa90233e259ad8f31b44af/runtime/lua/vim/filetype.lua#L1365

however I was using v0.9.5 (the latest stable release) which does not include this addition.

**Comment by konradmalik** [comment]
since tree-sitter is already available, I think it's ok to close this
