### ISSUE TITLE
Latest Earthly language keywords not highlighted

### ISSUE THREAD

**Issue by camerondurham** [earthly/earthly.vim#9]
Hi team,

Really small nit-pick about the plugin. It looks like the latest new keywords like `PROJECT`, `TRIGGER` and `PIPELINE` haven't been added here for syntax highlighting.

Example using latest plugin version:

<img width="240" alt="Earthly-Before" src="https://user-images.githubusercontent.com/17013462/224599136-d3beeef2-0631-4e50-bfb6-9880ff7ba131.png">

Was just using this example from the earthly.dev page for it.

![Screen Shot 2023-03-18 at 5 09 21 PM](https://user-images.githubusercontent.com/17013462/226146575-350ec089-fb41-4c86-9ea8-57240f7eb3e9.png)

I already made a quick 1-line PR #8 for this, and I ack that an issue probably is overkill but just wanted to document it here in case there was some discussion.

Would be cool (though I'm not really an ANTLR expert) if this could be automated so you didn't have to manually update keywords every time the language definition changed. I guess this is more along the lines of having a more editor agnostic tree-sitter implementation mentioned in #6.

Thanks!

*EDIT*: I realize this plugin is much much lower priority than VSCode, didn't notice there's already a step of the release process that handles updating VSCode extention which is nice: https://github.com/earthly/earthly/blob/923224f4b5d626c98f4a46d869cc505ce36fc2d9/release/README.md?plain=1#L133

**Comment by Velutas** [comment]
Update to keywords has now been merged in along with some other new keywords. Thanks for the issue!
